version: "3.4"

services:

  test_db:
    image: mysql
    container_name: test_db
    environment:
      MYSQL_DATABASE: 'test_case'
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    ports:
      - ${DB_HOST_PORT}:3306
    networks:
      - test_api

  test_api:
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx
    container_name: test_api
    ports:
      - ${NGINX_HOST_PORT}:80
    links:
      - test_php
    volumes:
      - ./api:/var/www/test_case
    depends_on:
      - test_php
    networks:
      - test_api

  test_php:
    build:
      context: .
      dockerfile: Dockerfile
      target: test_php
    container_name: test_php
    volumes:
      - ./api:/var/www/test_case
    environment:
      DB_HOST: test_db
      DB_PORT: 3306
      DB_USERNAME: root
      DB_DATABASE: test_case
      DB_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - test_api

networks:
  test_api:
    driver: bridge